<a href="https://colab.research.google.com/github/anamdias/anamdias/blob/main/TC3G.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving PNAD_COVID_092020.zip to PNAD_COVID_092020.zip
Saving PNAD_COVID_082020.zip to PNAD_COVID_082020.zip

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Dicionario_PNAD_COVID_092020_20220621.xls to Dicionario_PNAD_COVID_092020_20220621.xls
Saving Dicionario_PNAD_COVID_082020_20220621.xls to Dicionario_PNAD_COVID_082020_20220621.xls

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# ler o dicionário de setembro
dic = pd.read_excel("Dicionario_PNAD_COVID_092020_20220621.xls")

# mostrar primeiras linhas
dic.head()

,Dicionário das variáveis da PNAD COVID,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Tamanho,Código\nda\nvariável,Quesito,NaN,Categorias,NaN
1,NaN,NaN,nº,Descrição,Tipo,Descrição
2,Parte 1 - Identificação e Controle,NaN,NaN,NaN,NaN,NaN
3,4,Ano,NaN,Ano de referência,NaN,NaN
4,2,UF,NaN,Unidade da Federação,11,Rondônia

In [5]:
# ler o dicionário usando a linha 6 como cabeçalho
dic = pd.read_excel(
    "Dicionario_PNAD_COVID_092020_20220621.xls",
    header=3
)

# visualizar as primeiras linhas
dic.head()

     2   UF Unnamed: 2 Unidade da Federação  11  Rondônia
0  NaN  NaN        NaN                  NaN  12      Acre
1  NaN  NaN        NaN                  NaN  13  Amazonas
2  NaN  NaN        NaN                  NaN  14   Roraima
3  NaN  NaN        NaN                  NaN  15      Pará
4  NaN  NaN        NaN                  NaN  16     Amapá

In [6]:
# ler o dicionário de setembro
dic = pd.read_excel("Dicionario_PNAD_COVID_092020_20220621.xls")

# mostrar primeiras linhas
dic.head()

,Dicionário das variáveis da PNAD COVID,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Tamanho,Código\nda\nvariável,Quesito,NaN,Categorias,NaN
1,NaN,NaN,nº,Descrição,Tipo,Descrição
2,Parte 1 - Identificação e Controle,NaN,NaN,NaN,NaN,NaN
3,4,Ano,NaN,Ano de referência,NaN,NaN
4,2,UF,NaN,Unidade da Federação,11,Rondônia

In [8]:
# ler o dicionário usando a linha 6 como cabeçalho
dic = pd.read_excel(
    "Dicionario_PNAD_COVID_092020_20220621.xls",
    header=2
)

# visualizar as primeiras linhas
dic.head()

,Unnamed: 0,Unnamed: 1,nº,Descrição,Tipo,Descrição.1
0,Parte 1 - Identificação e Controle,NaN,NaN,NaN,NaN,NaN
1,4,Ano,NaN,Ano de referência,NaN,NaN
2,2,UF,NaN,Unidade da Federação,11,Rondônia
3,NaN,NaN,NaN,NaN,12,Acre
4,NaN,NaN,NaN,NaN,13,Amazonas

In [9]:
dic.columns = [
    "tamanho",
    "codigo_variavel",
    "numero_valor",
    "descricao_variavel",
    "tipo",
    "descricao_valor"
]

In [10]:
dic.head()

,tamanho,codigo_variavel,numero_valor,descricao_variavel,tipo,descricao_valor
0,Parte 1 - Identificação e Controle,NaN,NaN,NaN,NaN,NaN
1,4,Ano,NaN,Ano de referência,NaN,NaN
2,2,UF,NaN,Unidade da Federação,11,Rondônia
3,NaN,NaN,NaN,NaN,12,Acre
4,NaN,NaN,NaN,NaN,13,Amazonas

In [11]:
dic["codigo_variavel"].unique()

array([nan, 'Ano', 'UF', 'CAPITAL', 'RM_RIDE', 'V1008', 'V1012', 'V1013',
       'V1016', 'Estrato', 'UPA', 'V1022', 'V1023', 'V1030', 'V1031',
       'V1032', 'posest', 'A001', 'A001A', 'A001B1', 'A001B2', 'A001B3',
       'A002', 'A003', 'A004', 'A005', 'A006', 'A007', 'A008', 'A009',
       'B0011', 'B0012', 'B0013', 'B0014', 'B0015', 'B0016', 'B0017',
       'B0018', 'B0019', 'B00110', 'B00111', 'B00112', 'B00113', 'B002',
       'B0031', 'B0032', 'B0033', 'B0034', 'B0035', 'B0036', 'B0037',
       'B0041', 'B0042', 'B0043', 'B0044', 'B0045', 'B0046', 'B005',
       'B006', 'B007', 'B008', 'B009A', 'B009B', 'B009C', 'B009D',
       'B009E', 'B009F', 'B0101', 'B0102', 'B0103', 'B0104', 'B0105',
       'B0106', 'B011', 'C001', 'C002', 'C003', 'C004', 'C005', 'C0051',
       'C0052', 'C0053', 'C006', 'C007', 'C007A', 'C007B', 'C007C',
       'C007D', 'C007E', 'C007E1', 'C007E2', 'C007F', 'C008', 'C009',
       'C009A', 'C010', 'C0101', 'C01011', 'C01012', 'C0102', 'C01021',
       'C01022', 'C0103', 'C0104', 'C011A', 'C011A1', 'C011A11',
       'C011A12', 'C011A2', 'C011A21', 'C011A22', 'C012', 'C013', 'C014',
       'C015', 'C016', 'C017A', 'D0011', 'D0013', 'D0021', 'D0023',
       'D0031', 'D0033', 'D0041', 'D0043', 'D0051', 'D0053', 'D0061',
       'D0063', 'D0071', 'D0073', 'E001', 'E0021', 'E0022', 'E0023',
       'E0024', 'F001', 'F0021', 'F0022', 'F002A1', 'F002A2', 'F002A3',
       'F002A4', 'F002A5', 'F0061', 'F006'], dtype=object)

In [14]:
# Procurando variáveis relacionadas a sintomas

dic[dic["descricao_variavel"].str.contains("sintoma", case=False, na=False)]

,tamanho,codigo_variavel,numero_valor,descricao_variavel,tipo,descricao_valor
213,1,B0031,B3,Providência tomada para recuperar dos sintomas...,1,Sim
217,1,B0032,B3,Providência tomada para recuperar dos sintomas...,1,Sim
221,1,B0033,B3,Providência tomada para recuperar dos sintoma...,1,Sim
225,1,B0034,B3,Providência tomada para recuperar dos sintomas...,1,Sim
229,1,B0035,B3,Providência tomada para recuperar dos sintomas...,1,Sim
233,1,B0036,B3,Providência tomada para recuperar dos sintomas...,1,Sim
237,1,B0037,B3,Providência tomada para recuperar dos sintomas...,1,Sim

In [15]:
# Procurando palavaras específicas

dic[dic["descricao_variavel"].str.contains("febre|tosse|resp", case=False, na=False)]

,tamanho,codigo_variavel,numero_valor,descricao_variavel,tipo,descricao_valor
157,1,B0011,B1,Na semana passada teve febre?,1,Sim
161,1,B0012,B1,Na semana passada teve tosse?,1,Sim
169,1,B0014,B1,Na semana passada teve dificuldade para respirar?,1,Sim
270,1,B006,B6,"Durante a internação, foi sedado, entubado e c...",1,Sim
313,1,B0103,B10,Algum médico já lhe deu o diagnóstico de asma/...,1,Sim
638,2,F0061,F61,Quem respondeu ao questionário?,1,Pessoa moradora

In [16]:
variaveis_importantes = [
"B0011",
"B0012",
"B0013",
"B0014",
"B0015",
"B0019",
"B00110",
"B002",
"B005",
"C001",
"D001"
]

In [17]:
dic[dic["codigo_variavel"].isin(variaveis_importantes)][
["codigo_variavel","descricao_variavel"]
].drop_duplicates()

    codigo_variavel                                 descricao_variavel
157           B0011                      Na semana passada teve febre?
161           B0012                      Na semana passada teve tosse?
165           B0013            Na semana passada teve dor de garganta?
169           B0014  Na semana passada teve dificuldade para respirar?
173           B0015              Na semana passada teve dor de cabeça?
189           B0019                     Na semana passada teve fadiga?
193          B00110              Na semana passada teve dor nos olhos?
209            B002  Por causa disso, foi a algum estabelecimento d...
265            B005  Ao procurar o hospital, teve que ficar interna...
331            C001  Na semana passada, por pelo menos uma hora, tr...

In [18]:
# variáveis importantes escolhidas a partir do dicionário

variaveis_importantes = [
    "B0011",  # febre
    "B0012",  # tosse
    "B0013",  # dor de garganta
    "B0014",  # dificuldade respiratória
    "B0015",  # dor de cabeça
    "B0019",  # fadiga
    "B00110", # perda de olfato

    "B002",   # procurou atendimento
    "B005",   # fez teste

    "C001",   # trabalhou
    "D001"    # recebeu auxílio
]

In [19]:
# verificar se as colunas existem na base
[col for col in variaveis_importantes if col in df.columns]

NameError: name 'df' is not defined

In [20]:
import pandas as pd

# ler arquivo de agosto
aug = pd.read_csv("PNAD_COVID_082020.csv", sep=";", encoding="latin1")

# ler arquivo de setembro
sep = pd.read_csv("PNAD_COVID_092020.csv", sep=";", encoding="latin1")

FileNotFoundError: [Errno 2] No such file or directory: 'PNAD_COVID_082020.csv'

In [21]:
import os

os.listdir()

['.config',
 'Dicionario_PNAD_COVID_082020_20220621.xls',
 'Dicionario_PNAD_COVID_092020_20220621.xls',
 'PNAD_COVID_092020.zip',
 'PNAD_COVID_082020.zip',
 'sample_data']